# Generated by Django 5.2.8 on 2025-11-20 06:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_type', models.CharField(choices=[('rate_limit', 'Rate Limiting'), ('password_policy', 'Password Policy'), ('session_policy', 'Session Policy'), ('encryption', 'Encryption'), ('audit', 'Audit Logging')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['setting_type'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('permission_change', 'Permission Change'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('security_violation', 'Security Violation'), ('unauthorized_access', 'Unauthorized Access'), ('api_access', 'API Access'), ('failed_login', 'Failed Login'), ('suspicious_activity', 'Suspicious Activity')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_type', models.CharField(choices=[('ip', 'IP Address'), ('user', 'User'), ('api_key', 'API Key')], db_index=True, max_length=20)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(db_index=True, max_length=500)),
                ('request_count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['limit_type', 'identifier'], name='security_ra_limit_t_b56ae7_idx'), models.Index(fields=['endpoint', 'window_start'], name='security_ra_endpoin_b1625f_idx'), models.Index(fields=['is_blocked', 'blocked_until'], name='security_ra_is_bloc_ada5c2_idx')],
                'unique_together': {('limit_type', 'identifier', 'endpoint', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('sql_injection', 'SQL Injection Attempt'), ('xss', 'Cross-Site Scripting'), ('csrf', 'CSRF Attack'), ('unauthorized_access', 'Unauthorized Access'), ('suspicious_ip', 'Suspicious IP Activity'), ('malware_upload', 'Malware Upload Attempt'), ('data_breach', 'Data Breach Attempt'), ('api_abuse', 'API Abuse')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('ignored', 'Ignored')], db_index=True, default='active', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detection_data', models.JSONField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_audit_logs', models.ManyToManyField(blank=True, related_name='security_events', to='security.auditlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_type', models.CharField(choices=[('service', 'Service Account'), ('user', 'User API Key'), ('integration', 'Third-party Integration')], default='user', max_length=20)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='security_ap_user_id_e173a4_idx'), models.Index(fields=['key', 'is_active'], name='security_ap_key_189f43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'event_type'], name='security_au_user_id_400386_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='security_au_event_t_13b3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='security_au_severit_eb201b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='security_au_ip_addr_f227e7_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'status'], name='security_se_event_t_743866_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'created_at'], name='security_se_severit_187aea_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address', 'created_at'], name='security_se_ip_addr_1bac92_idx'),
        ),
    ]
