"""
Django REST Framework Default Configuration
============================================

Defines the ``REST_FRAMEWORK`` dictionary consumed by DRF on startup.
Every setting here applies globally to all API views unless explicitly
overridden at the view or viewset level.

Key decisions:
- **Authentication**: JWT-only (``JWTAuthentication``). Session auth is
  disabled for APIs; it is available through ``dj-rest-auth`` cookie
  config if ever re-enabled.
- **Permissions**: ``DjangoModelPermissions`` as the global default so
  that every model-backed view requires appropriate Django permissions.
  Override per-view with ``AllowAny``, ``IsAuthenticated``, etc.
- **Renderers**: JSON + BrowsableAPI. Remove ``BrowsableAPIRenderer``
  in production via the ``production.py`` override if desired.
- **Filtering/Search/Ordering**: ``DjangoFilterBackend`` + DRF's
  ``SearchFilter`` and ``OrderingFilter`` are enabled project-wide.
- **Pagination**: Handled by ``apps.core.pagination.StandardResultsSetPagination``.
- **Schema**: ``drf_spectacular.openapi.AutoSchema`` drives the OpenAPI
  spec generated by the ``/api/v1/schema/`` endpoint.

Reference: https://www.django-rest-framework.org/api-guide/settings/
"""

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # For development
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.StandardResultsSetPagination",
    # "DEFAULT_THROTTLE_CLASSES": [
    #     "rest_framework.throttling.AnonRateThrottle",
    #     "rest_framework.throttling.UserRateThrottle",
    # ],
    # "DEFAULT_THROTTLE_RATES": {
    #     "anon": "100/hour",
    #     "user": "1000/hour",
    #     "content_generation": "60/minute",
    #     "assessment_generation": "20/minute",
    #     "agent_request": "100/minute",
    #     "burst": "10/minute",
    # },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
