# Generated by Django 5.2.8 on 2026-01-19 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="School Management System", max_length=255
                    ),
                ),
                ("site_url", models.URLField(default="http://localhost:3000")),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                ("time_format", models.CharField(default="24h", max_length=10)),
                (
                    "session_timeout",
                    models.IntegerField(
                        default=30, help_text="Session timeout in minutes"
                    ),
                ),
                ("max_login_attempts", models.IntegerField(default=5)),
                ("password_min_length", models.IntegerField(default=8)),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False, help_text="Require two-factor authentication"
                    ),
                ),
                ("allow_user_registration", models.BooleanField(default=False)),
                (
                    "email_from_name",
                    models.CharField(default="School Admin", max_length=255),
                ),
                (
                    "email_from_address",
                    models.EmailField(default="noreply@school.com", max_length=254),
                ),
                ("smtp_host", models.CharField(default="localhost", max_length=255)),
                ("smtp_port", models.IntegerField(default=587)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_push_notifications", models.BooleanField(default=False)),
                ("notification_retention_days", models.IntegerField(default=30)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("debug_mode", models.BooleanField(default=False)),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("cache_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
