# Generated by Django 5.2.8 on 2025-11-20 07:00

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, help_text='Not used for authentication - kept for compatibility', max_length=150, null=True)),
                ('email', models.EmailField(help_text='Primary email address for authentication', max_length=254, unique=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID for organizational tracking', max_length=50, null=True, unique=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='When the account lock expires', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last successful login', null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the user account has been approved by an administrator')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email or identity')),
                ('must_change_password', models.BooleanField(default=False, help_text='Whether the user must change their password on next login')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='When the password was last changed', null=True)),
                ('backup_codes', models.JSONField(blank=True, help_text='Backup codes for 2FA recovery', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique role identifier', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable role name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='user_roles', to='auth.permission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role for permissions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.userrole'),
        ),
        migrations.CreateModel(
            name='UserRoleHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Reason for the role change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the role change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('new_role', models.ForeignKey(blank=True, help_text='New role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_to', to='accounts.userrole')),
                ('old_role', models.ForeignKey(blank=True, help_text='Previous role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_from', to='accounts.userrole')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose role was changed', on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the session')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('device_type', models.CharField(blank=True, help_text='Type of device used', max_length=50)),
                ('device_os', models.CharField(blank=True, help_text='Operating system of device', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser used for session', max_length=50)),
                ('location_info', models.JSONField(blank=True, help_text='Geographic location information', null=True)),
                ('device_info', models.JSONField(blank=True, help_text='Parsed device information from user agent', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this session was revoked (if applicable)', null=True)),
                ('expires_at', models.DateTimeField(help_text='When this session expires')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address used for login attempt', max_length=254)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the login attempt')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for tracking', max_length=255)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure', max_length=100)),
                ('location_info', models.JSONField(blank=True, help_text='Geographic location information', null=True)),
                ('device_type', models.CharField(blank=True, help_text='Type of device used', max_length=50)),
                ('device_os', models.CharField(blank=True, help_text='Operating system of device', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser used for login', max_length=50)),
                ('success', models.BooleanField(default=False, help_text='Whether the login attempt was successful')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this attempt (if successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_lo_email_a84d38_idx'), models.Index(fields=['user'], name='accounts_lo_user_id_2a8aa2_idx'), models.Index(fields=['success'], name='accounts_lo_success_3a0026_idx'), models.Index(fields=['created_at'], name='accounts_lo_created_597055_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_1f2a14_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, help_text='User biography')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or division', max_length=100)),
                ('job_title', models.CharField(blank=True, help_text='Job title or position', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='User approval status', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this profile was approved', null=True)),
                ('preferred_language', models.CharField(default='en', help_text="User's preferred language code", max_length=10)),
                ('interface_theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('auto', 'Auto Theme')], default='light', help_text='User interface theme preference', max_length=20)),
                ('allow_notifications', models.BooleanField(default=True, help_text='Whether to allow email notifications')),
                ('show_email', models.BooleanField(default=False, help_text='Whether to show email address publicly')),
                ('show_phone', models.BooleanField(default=False, help_text='Whether to show phone number publicly')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_us_user_id_806298_idx'), models.Index(fields=['status'], name='accounts_us_status_aa9625_idx'), models.Index(fields=['created_at'], name='accounts_us_created_70c995_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['name'], name='accounts_us_name_23470c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['created_at'], name='accounts_us_created_cf74dd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_id_566c09_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolehistory',
            index=models.Index(fields=['user'], name='accounts_us_user_id_aecaef_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolehistory',
            index=models.Index(fields=['changed_by'], name='accounts_us_changed_bb9ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='userrolehistory',
            index=models.Index(fields=['created_at'], name='accounts_us_created_641aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='accounts_us_user_id_691a59_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='accounts_us_session_511f42_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['revoked_at'], name='accounts_us_revoked_93d8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_3fa67a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='accounts_us_last_ac_a630f7_idx'),
        ),
    ]
