# Generated by Django on 2026-01-19
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("otp_totp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_device",
            field=models.OneToOneField(
                blank=True,
                help_text="TOTP device for two-factor authentication",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_user",
                to="otp_totp.totpdevice",
            ),
        ),
    ]
