# Generated by Django 5.2.8 on 2025-11-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_device',
            field=models.OneToOneField(blank=True, help_text='TOTP device for two-factor authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='otp_totp.totpdevice'),
        ),
    ]
