# Generated by Django 5.2.8 on 2025-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_certification_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='certification_level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Whether to show email address publicly'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Whether to show phone number publicly'),
        ),
    ]
