# Generated by Django 5.2.8 on 2025-11-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_info',
            field=models.JSONField(blank=True, help_text='Parsed device information from user agent', null=True),
        ),
    ]
