# Generated by Django 5.2.8 on 2025-11-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersession_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Risk score for this session (0-100)'),
        ),
    ]
