# Generated by Django 5.2.8 on 2025-11-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_risk_score'),
        ('django_otp', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, help_text='Backup codes for 2FA recovery', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_device',
            field=models.OneToOneField(blank=True, help_text='TOTP device for two-factor authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='django_otp.totpdevice'),
        ),
    ]
